"""Database creation

Revision ID: 099b169e19ac
Revises: 
Create Date: 2024-05-06 17:23:47.802298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '099b169e19ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Roles_id_seq"\'::regclass)'),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('permission', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='Roles_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('Users',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_id_seq"\'::regclass)'),
                              autoincrement=True, nullable=False),
                    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('registration_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['Roles.id'], name='Users_role_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='Users_pkey')
                    )
    # ### end Alembic commands ###
